### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by andrelandgraf** [tum-aweink/high5-learning-frontend#1]
A Landing Page with Login / Register Buttons / Components.

**Comment by andreweinkoetz** [comment]
Lovely background ❤️ 
But i got this error when loading the page?
![image](https://user-images.githubusercontent.com/14924669/40622135-50227eb8-62a0-11e8-8668-2309b3506aa3.png)

**Comment by andrelandgraf** [comment]
Fixed 👍

**Comment by andrelandgraf** [comment]
Reminder: when the user comes from gotocass/:id root back to this url instead of myclasses/ when login or register has been done.

**Comment by andrelandgraf** [comment]
Reminder: Exercise 3: implement basic form validation double check my validation for login and register.
