### ISSUE TITLE
Something is already running on port 3000

### ISSUE THREAD

**Issue by andrelandgraf** [tum-aweink/high5-learning-frontend#12]
Do we have any global solution to switch the port of the frontend yet?

I have switched the backend now to port 3010 (see backend config.js). This means the problem is now solved, but still, just wondering if we have found any global solution for the frontend?

**Comment by andreweinkoetz** [comment]
To fix the problem of running both applications on port 3000 you need to add a file called `.env` with the line `PORT=3001` to your local project setup (e.g. in root folder). See in our wiki [lessons learned](https://github.com/tum-aweink/high5-learning-frontend/wiki)

**Comment by andrelandgraf** [comment]
Perfect, thanks!
