### ISSUE TITLE
Create routes for our components

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#16]
Routes have to be created for each separate component to be rendered. In order to achieve separation between authenticated users and visitors, we have to check if the jwt is set. Additionally, we have to check if the current user is a teacher or a student.

**Comment by HmG248** [comment]
I have a question regarding the route for a homework: Wouldn't it make more sense to have a route for a homework with a path: "/myclasses/:classid/homework/:homeworkid? Such a structure would definitely make it a lot more easier for me to implement the breadcrumbs for a homework than the current path structure: "homework/:homeworkid"
