### ISSUE TITLE
Homework Component

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#17]
The homework component is responsible for displaying a single homework in a class, as a class contains many homework, also a wrapping list component is needed.

**Comment by ghost** [comment]
I think we don't need this check in this component any more:

`{(!props.homeworkVisible && !UserService.isTeacher())`

Now the teacher/student check is in the HomeworkDetailView component. 
At the moment as a student no homework is displayed.

What do you mean?

**Comment by andreweinkoetz** [comment]
No i don't think we need this anymore so let's remove it :)
