### ISSUE TITLE
Register & Login Forms

### ISSUE THREAD

**Issue by andrelandgraf** [tum-aweink/high5-learning-frontend#2]

**Comment by andrelandgraf** [comment]
If Type == Teacher, we need another input field for the license code. 
-> Do Dump Data for schools first. Backend #2 -> Done. See backend repo for dump data.

**Comment by andrelandgraf** [comment]
@tum-aweink 

We receive an error at the backend when we log out in class list view. 
"TypeError: Cannot read property 'substring' of undefined" 

I will try to solve this. 🔢

**Comment by andreweinkoetz** [comment]
This is caused by the substring method i implemented in the middleware. I think it's sufficient to simply check if the value of the token-header field is empty or not.

**Comment by andrelandgraf** [comment]
So you renamed the token and therefore you had to edit middleware.js and added the substring method? I will simply delete the substring call then, is this alright?

**Comment by andreweinkoetz** [comment]
No i renamed the selector for the header array because x-access-token is not included in the header.
![image](https://user-images.githubusercontent.com/14924669/40623433-5a0d22a0-62a7-11e8-91a0-ab86ad7809ca.png)
The substring call is mandatory, because the token is stored as 'JWT (token_value_goes_here)' - so you need to get rid of that first 4 letters.

**Comment by andrelandgraf** [comment]
`    if(req.headers['authorization'] !== undefined){
        const token = req.headers['authorization'].substring(4);
    }`

So we just have to shield against undefined after logout has been called.

**Comment by andreweinkoetz** [comment]
That's it 👍

**Comment by andrelandgraf** [comment]
Already deleted my comment, sorry. I receive more errors (also frontend) when I do check against undefined. Give me a second to dive into the code.
