### ISSUE TITLE
ClassDetailView --> field "assignedClass" is not set

### ISSUE THREAD

**Issue by ghost** [tum-aweink/high5-learning-frontend#24]
In the component ClassDetailView the field "assignedClass" is not set. 
Do we need this, as it is not required by the HomeworkModel.

**Comment by andreweinkoetz** [comment]
Could you please give me more info about this e.g. the line of code where this field is used?

**Comment by andrelandgraf** [comment]
He is talking about the field assingedClass in the Homework Model that contains a Object Id to the class. The named field is never set in the controller, nor does the front end address this field.  As the field is not required by definition of Homework Model, we never received an error. 

I would like to have this field required = true and set. I know it is not needed as we have the Class Model with the homework array but for the statistic, aggregating the member of the class of the homework would be a bit easier with the field required. :-)

**Comment by andreweinkoetz** [comment]
See current HEAD revision 👍
