### ISSUE TITLE
Homework Detail View: Remove isTeacher from state

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#25]
We use the type of the currently logged in user to decide wether or not we show the cancel and submit button. This is achieved by saving the type of the user in state - although the type of the current user can be easily identified by calling UserService.isTeacher(), which simply checks the token instead of calling the backend.

**Comment by HmG248** [comment]
I do call UserService.isTeacher() in componentWillMount and then set isTeacher

**Comment by andreweinkoetz** [comment]
I know but why do you use it afterwards as state instead of calling the UserService? In my opinion we should use less state and therefore replace the state with service calls.

**Comment by andreweinkoetz** [comment]
This issue is no longer needed since we split the view for different user types #26
