### ISSUE TITLE
Discussion of structure of HomeworkDetailView

### ISSUE THREAD

**Issue by ghost** [tum-aweink/high5-learning-frontend#26]
At the moment the component HomeworkDetailView has a lot of functionality:
(doing homework/ display of one homework/ display of statistics)
- student/doing homework: student sees the exercise list and can do the exercises

- student/homework submitted: after submission the student should not be able to fill out again and should see the submitted solution

- teacher/homework: teacher can see all statistics and individual ones

Do you think it is a good idea to split the HomeworkDetailView in a StatisticsView (teacher and student) and a HomeworkDetailView (only student doing homework)?

**Comment by andreweinkoetz** [comment]
I think we should use this view only for the student. The teacher gets another view for the statistics. Therefore he will be redirected when entering a single homework.

**Comment by HmG248** [comment]
I agree, it makes more sense to have a separate component for a separate use case
