### ISSUE TITLE
Provide basic error handling and user notifications

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#27]
Taken from description of exercise 3:

> The web application is considered to be finished if it supports at least four distinct use cases which are specific to your business model. Furthermore, in addition to those use cases, your web application has to:
>  - provide basic error handling and user notifications

Currently we do not notify the user in an appropriate way. Sometimes we just log the error or call alert() - this is not user-friendly and not informative. I suggest that we build upon the error component that was introduced by @HmG248 a new more generic component that is called when one of the service calls fails. Here is an example:

Component: ClassListView
Method: componentWillMount
Service call: UserService
```
ClassService.getClassesOfUser().then((data) => {
            this.setState({
                classes: [...data],
                loading: false
            });
        }).catch((e) => {
            console.error(e);
        });
```

Suggestion:
1. Add error to state:
```
error : {
                fired: false,
                errorCode: 0,
                errorMsg: ''
            },
```
2. If error occured, setState in catch-block
```
ClassService.getClassesOfUser().then((data) => {
            this.setState({
                classes: [...data],
                loading: false
            });
        }).catch((e) => {
            this.setState({error: {fired: true, errorCode: e.Code, errorMsg: e.Msg}});
        });
```
3. Check the error state make the generic ErrorComponent visible:
```
<ErrorComponent
                    visible={this.state.error.fired}
                    error={this.state.error}
                    closeDialog={()=>{this.setState(
                        {error:
                                {
                                    fired:false,
                                    errorCode:0,
                                    errorMsg:''
                                }
                        })
                    }}
                />
```
4. The error component can use the error object to display an informative message to the user:
![image](https://user-images.githubusercontent.com/14924669/40884443-1153377c-6714-11e8-9f8e-ea92a32d0d7a.png)

**Comment by andreweinkoetz** [comment]
I made some checks and this approach is even working within modal dialogs:
![image](https://user-images.githubusercontent.com/14924669/40884580-8008b30c-6716-11e8-80e2-caeb21afe99a.png)

**Comment by andrelandgraf** [comment]
I like it! Will implement the error component for login and register! :-)

**Comment by andreweinkoetz** [comment]
@andrelandgraf You actually don't have to - I create a generic Exception component which will be invoked from App.js so you basically call this.props.handleException(error) - that's it 😃

**Comment by andreweinkoetz** [comment]
So this is working as a snackbar now. Please have a look at the ExceptionComponent to see how you call it
