### ISSUE TITLE
Implement the CRUD methods 

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#28]
Taken from exercise 3:

> The web application is considered to be finished if it supports at least four distinct use cases which are specific to your business model. Furthermore, in addition to those use cases, your web application has to:
> 
> - provide read and write access to your model, i.e., you have to implement the CRUD methods (Create, Read, Update, Delete) for **at least one** of your model classes

Currently we do not implement any Update or Delete method in our project.
This issue is for discussing the model we use as well as who is responsible for it.

**Comment by andreweinkoetz** [comment]
Delete class including all attached homework and update the title and description of a homework

**Comment by andrelandgraf** [comment]
Updating classes would be dead simple and probably super straight forward as we just have to reopen the model dialogue with the right prop parameters.

Deleting a class is more of a hassle in the backend as deleting a class means:
- homework deletion
- delete all submissions to those homeworks
- delete membership in all the users (teacher and student) that were part of the class
- and finally deleting the class itself

Updating an homework would be way more complicated as reloading the modal dialogue with all the exercises seems more complicated. 

Deleting a homework would be easier though, just deletion of submissions and the homework itself.

**Comment by andreweinkoetz** [comment]
As we now have to add the students manually, please update the CRUD methods for the classes dialog

**Comment by HmG248** [comment]
@tum-aweink 
I refactored the ClassListView and ModalDialogNewClass component as best as I could
Imo it is way better structured than before, but I wanted to ask you whether you could integrate selectedItems of ModalDialogNewClass into classToAdd? Or is there a reason, why you didn't do it in the first place?

**Comment by andreweinkoetz** [comment]
Of course you can integrate it - at the time i was implementing the adding students to a class, i kept it separate as we used the submit method in the parent component and therefore it was not necessary. If you have switched all state handling into the modal component you can of course simply use the class object.
