### ISSUE TITLE
Render modal dialogs only when visible

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#37]
We should not render all modals instantly but only when the modal is called.

Like:

```
const modal = this.state.visible ? <Modal /> : null;

render() {
   return (
      {modal}
   );
}
```

**Comment by andrelandgraf** [comment]
FYI: switch statement if you have more then "if else" cases 👍 
https://react-cn.github.io/react/tips/if-else-in-JSX.html

**Comment by andrelandgraf** [comment]
Done for register and login :)
