### ISSUE TITLE
Class/Homework: Fill expansion panels for class and homework with useful information for teachers and students

### ISSUE THREAD

**Issue by andrelandgraf** [tum-aweink/high5-learning-frontend#46]

**Comment by andreweinkoetz** [comment]
Idea for homework panel as a student:
Display his/her position of submission, i.e. display a line that says:
_You were ##3 to submit this homework_
And if he/she is the first one, we could additionally display a [cake icon](https://material.io/tools/icons/?search=cake&icon=cake&style=baseline)
--> This would be some sort of "gamification" :)

**Comment by andreweinkoetz** [comment]
![image](https://user-images.githubusercontent.com/14924669/41464011-dfba69f4-7098-11e8-9a63-3164887d9326.png)
We can discuss about the icon and/or the text, but the functionality is implemented and working :)

**Comment by andrelandgraf** [comment]
@ge98hod I just commited two first ideas for the homework and class expansion panels of the teacher. :)
