### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#50]
@All please fix the warnings in your components - additionally please remove your console.log statements before committing as it makes it very hard to differentiate between your logging statements and your own. 

![image](https://user-images.githubusercontent.com/14924669/41199436-672b159c-6c92-11e8-82ef-26f7e081f26e.png)

Especially for warnings like Line136: Please make sure to use '===' and if it's not working check out why instead of simply using the non-strict variant '=='.

**Comment by andreweinkoetz** [comment]
Only warning left is related to regex

**Comment by ghost** [comment]
When I log in as a teacher and go inside a homework this warning is displayed

<img width="548" alt="bildschirmfoto 2018-06-13 um 08 42 03" src="https://user-images.githubusercontent.com/39064712/41334393-c1477796-6ee5-11e8-85a1-c00246c8ceec.png">

I can't find the reason for this warning in the HomeworkDetailViewTeacher ....

**Comment by andreweinkoetz** [comment]
![image](https://user-images.githubusercontent.com/14924669/41466071-ea64de7c-70a0-11e8-994e-53df39a6022f.png)
You simply needed to change the width-value to a number (was '60px') :)

**Comment by ghost** [comment]
Nice!

Andre Weinkoetz <notifications@github.com> schrieb am Fr., 15. Juni 2018,
13:36:

**Comment by andreweinkoetz** [comment]
@ALL please fix the remaining warnings:

![image](https://user-images.githubusercontent.com/14924669/41466302-f817114c-70a1-11e8-8fea-47046f23372c.png)
