### ISSUE TITLE
No homework displayed in ClassDetailView

### ISSUE THREAD

**Issue by ghost** [tum-aweink/high5-learning-frontend#52]
Although this student is assigned to this class with an existing homework, nothing is displayed. This bug is only in the ClassDetailView of the student. 

<img width="830" alt="bildschirmfoto 2018-06-11 um 08 13 58" src="https://user-images.githubusercontent.com/39064712/41215277-e3e44672-6d4f-11e8-862c-a509ad8b4f86.png">

**Comment by andreweinkoetz** [comment]
Is the homework set to visible?
![image](https://user-images.githubusercontent.com/14924669/41215355-40f56274-6d50-11e8-9a46-09c513513d6c.png)

**Comment by ghost** [comment]
Ok that's it :D
