### ISSUE TITLE
Error when clicking on register button on landing page

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#53]
Possibly just a minor bug:

![image](https://user-images.githubusercontent.com/14924669/41228679-7477f458-6d79-11e8-8fd2-d6f74282c5f4.png)

Happens directly after clicking on the Register button

**Comment by andrelandgraf** [comment]
This is an optimization warning for react. React can do better DOM-Optimization with keys for every row in an array. Added that.
