### ISSUE TITLE
Improve RegisterDialog

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#54]
The register dialog could be reworked in order to only display the label "School" unless a school is chosen (e.g. same behaviour as username and password fields):
![image](https://user-images.githubusercontent.com/14924669/41228841-0e59c240-6d7a-11e8-8533-5d82b5a04114.png)

**Comment by andrelandgraf** [comment]
I love the idea, implemented it!

**Comment by andrelandgraf** [comment]
Check out this nice and handy syntactic sugar for "IF true do something, else nothing": 
`{(this.state.school === "") && <InputLabel htmlFor="school-helper">School&nbsp;&nbsp;</InputLabel>}`
