### ISSUE TITLE
ClassList

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#6]

**Comment by andreweinkoetz** [comment]
This has to be wrapped when using a REST call - see #13

**Comment by andrelandgraf** [comment]
@tum-aweink This comment is just a reminder about the workflow of the frontend and I wanted to let you know before I make any changes to app.js anyway. The render function should work like: if isLoggedIn() -> return ClassList (as you implemented it already) else -> return LandingPage. 

I will not change this yet, so you guys can still test your features without thinking about auth, but I will do this locally for me already.

**Comment by andreweinkoetz** [comment]
@andrelandgraf We should have a look together at the entire login, auth-procedure in order to make sure that we are on the same page when it comes to switching views for different users. Therefore i suggest that we open a separate issue where we can focus all q/a regarding this topic
