### ISSUE TITLE
ClassList / Breadcrub Errors & Warning

### ISSUE THREAD

**Issue by andrelandgraf** [tum-aweink/high5-learning-frontend#60]
![classlist](https://user-images.githubusercontent.com/15163028/41303063-7bd1357c-6e6c-11e8-8e05-d2b58d93cefc.PNG)

I receive those errors and warnings when the landingPage forwards me after registration or login.

**Comment by andreweinkoetz** [comment]
It's all related to the breadcrumb component. Actually the Grid components are simply mixed up (easy). 
![image](https://user-images.githubusercontent.com/14924669/41303199-caf1f61e-6e6c-11e8-97c1-67858693bb96.png)
Can you fix this? @HmG248

**Comment by HmG248** [comment]
fixed
