### ISSUE TITLE
Forbidden 403 in ClassDetailView

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#64]
I got an error message in ClassDetailView when i am logged in as a student:

![image](https://user-images.githubusercontent.com/14924669/41466148-4cb80b4e-70a1-11e8-9dd3-d152fbacafec.png)

To avoid this we will need to check wether the logged in user is a student or a teacher and only call `ClassService.getAllHomeworkOfUser()` if the user is a teacher.

As you might be currently working on this, I assigned this issue to you but i can solve it too if you want me to :)

**Comment by HmG248** [comment]
fixed
