### ISSUE TITLE
Create useful test-data for presentation

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#65]
For the presentation we need to come up with some test-data such as:

- schools
- users
- classes
- homework
- submission

We should use an easy naming convention such as:
- Teacher: teacher<number or subject (e.g. math)>@<schoolname>.com
- Student: student<number or subject (e.g. math) or schoolyear>@<schoolname>.com

Additionally we need to talk about which workflows we want to present.
- use cases in order (register, create class + hw, login as student, do homework?)
- use cases with different users and test-data (login as studentX do homework, login as teacherX to check homework)
- sth. different?

**Comment by HmG248** [comment]
I suggest we talk about this in person :)

**Comment by andreweinkoetz** [comment]
To be tracked in backend
