### ISSUE TITLE
Beautify CreateHomework Dialog

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#66]
Currently the design does not tell the user for what the upper dropdown fields can be used. Additionally they do not align to the textinput fields below (e.g. title)

![image](https://user-images.githubusercontent.com/14924669/41545913-860fb04a-731c-11e8-929a-43a105a329bd.png)

I would suggest that there is a headline 'Copy previous homework' and that the size of the dropdowns match the sizes of the textfields

**Comment by andreweinkoetz** [comment]
When in mobile view - many selections overlap in copy homework:

![image](https://user-images.githubusercontent.com/14924669/41645455-600a6cd6-7471-11e8-929a-2b7a903086f6.png)

**Comment by andreweinkoetz** [comment]
I wrote a basic fix for this: 
![image](https://user-images.githubusercontent.com/14924669/41645509-817b5fa6-7471-11e8-862d-26b6c88211e4.png)

If you are fine with it, i will upload it

**Comment by andreweinkoetz** [comment]
I would additionally fix the spacing of the buttons when adding new exercises:

Current:
![image](https://user-images.githubusercontent.com/14924669/41647048-9305415c-7475-11e8-8982-ab3295fec9f0.png)

Fix:
![image](https://user-images.githubusercontent.com/14924669/41647238-1f062d9c-7476-11e8-9a06-4979e9f96238.png)

**Comment by HmG248** [comment]
Looks very nice, you can of course upload it 👍
