### ISSUE TITLE
Beautify Teacher Statistic View (mobile only)

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#67]
When you view the mobile site of the teacher statistics, most of the statistics overlap. 
![image](https://user-images.githubusercontent.com/14924669/41546117-1903776a-731d-11e8-8185-3e238b12fbb4.png)
I would suggest we use other ways to display the content in mobile view.
E.g. we could show the Statistics in the upper part of the page in two separate paper components instead of one. This could be done by using the Hidden component in combination with with the only property.

**Comment by ghost** [comment]
<img width="318" alt="bildschirmfoto 2018-06-20 um 21 07 19" src="https://user-images.githubusercontent.com/39064712/41679292-f79d0c64-74cd-11e8-8795-e10837acafef.png">
