### ISSUE TITLE
Remove unused code block

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#69]
![image](https://user-images.githubusercontent.com/14924669/41808890-f6e3b98a-76e4-11e8-97d5-37f1a85aaab5.png)

Those two methods in ClassDetailView are not used (only handleSwitchChange) in Homework component.
Could you please confirm that and make sure to remove all occurrences (definition, usage and propagation to children)? 
Please update your project before (i've put `//not used ` behind the usages) :-)

**Comment by HmG248** [comment]
done
