### ISSUE TITLE
Navbar, Breadcrumb: Hermann

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#7]

**Comment by andreweinkoetz** [comment]
Temporary page layout contains placeholders for these elements

**Comment by andreweinkoetz** [comment]
Just FYI - i think i found a way to navigate via the components name (e.g. /myclasses/math/homework/firsthomework) including a working breadcrumb navigation. I will publish my approach as soon as i finish my tests.

**Comment by andreweinkoetz** [comment]
I forgot to mention that we still need to update the styling 😃

**Comment by HmG248** [comment]
Looks nice! Cool work! And your code is way more leaner than mine 🙂 
Well, we have to update the styling for nearly every component 😆

**Comment by HmG248** [comment]
I noticed a bug: when you are in a homework and you want to go back to the  detail view of the class through the breadcrumbs, it doesn't load the class but only shows the loading icon

**Comment by andreweinkoetz** [comment]
![image](https://user-images.githubusercontent.com/14924669/41095142-ce64e2a4-6a50-11e8-8f36-90011e51ad3d.png)
Your reformatting deleted the c from classId. Please be more careful when refactoring code ;)

**Comment by HmG248** [comment]
ups, my bad, I will try to take more care when refactoring 😬

**Comment by andreweinkoetz** [comment]
Student can see administrative options in navbar:
![image](https://user-images.githubusercontent.com/14924669/41189821-168dcbd4-6bd4-11e8-8083-ab4a4b3c2eb9.png)

**Comment by andreweinkoetz** [comment]
Basic functionality is working. For design issue please see #44
