### ISSUE TITLE
Modal Dialogs (create homework, create class)

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#8]

**Comment by andreweinkoetz** [comment]
https://react-md.mlaursen.com/components/dialogs

**Comment by andrelandgraf** [comment]
We could think about deleting the cancel button in our modal dialogues (including login / register)  and calling the cancel event by clicking back / escape or outside the focus of the modal dialogue. This is obviously optional, but I am already annoyed to click the cancel button every time I am testing the functionalities.

**Comment by HmG248** [comment]
This was intentionally done, because users can click pretty easily on something else than a modal dialog and therefore I disabled canceling events by clicking back/escape

**Comment by andrelandgraf** [comment]
@HmG248 alright! :)

**Comment by andreweinkoetz** [comment]
Delete exercise buttons are floating between answer possiblities. Is this intended behaviour?
![image](https://user-images.githubusercontent.com/14924669/41189967-8180c566-6bd6-11e8-8798-5ae08a4abdad.png)

**Comment by HmG248** [comment]
No, I want to redesign the modal dialog, but I suck at design 😝
